# CI 项目名称
name: 编译-360-T7

# CI 触发计划
on:
  # 自动编译：当 "Auto-Clean" 工作流程运行完成后触发
  workflow_run:
    workflows: ["自动清理"]
    types:
      - completed
  # 手动编译：允许手动触发此工作流程
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

# CI 任务权限
# 给予所有任务读写权限
permissions: write-all

# CI 执行任务
jobs:
  build:
    # 任务名称将显示为矩阵中的 CONFIG 值
    name: ${{matrix.CONFIG}}
    # 任务执行策略
    strategy:
      # 当一个任务失败时，不取消其他正在运行的任务
      fail-fast: false
      # 定义编译矩阵
      matrix:
        CONFIG: [360-T7]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [owrt]

    # 调用可复用的编译核心工作流程
    uses: ./.github/workflows/WRT-CORE.yml
    # 传递给核心工作流程的参数
    with:
      # 编译配置文件名
      WRT_CONFIG: ${{matrix.CONFIG}}
      # 默认主题
      WRT_THEME: argon
      # 默认主机名
      WRT_NAME: OpenWrt
      # 默认 WiFi 名称
      WRT_SSID: OpenWrt
      # 默认 WiFi 密码
      WRT_WORD: 12345678
      # 默认 LAN IP 地址
      WRT_IP: 10.0.2.1
      # 默认登录密码 (仅作提示，修改无效)
      WRT_PW: 无
      # 源码仓库链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      # 源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      # 源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      # 手动调整的插件包
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      # 是否仅测试配置文件 (不编译)
      WRT_TEST: ${{inputs.TEST}}
