# CI 项目名称
name: 测试编译

# CI 触发计划
on:
  # 手动编译：允许手动触发此工作流程
  workflow_dispatch:
    inputs:
      CONFIG:
        description: '选择要测试的配置文件'
        default: 'MEDIATEK'
        required: true
        type: choice
        options:
          - MEDIATEK
          - ROCKCHIP
          - X86
          - IPQ50XX-WIFI-YES
          - IPQ50XX-WIFI-NO
          - IPQ60XX-WIFI-YES
          - IPQ60XX-WIFI-NO
          - IPQ807X-WIFI-YES
          - IPQ807X-WIFI-NO
          - TEST
      SOURCE:
        description: '选择要编译的源码'
        default: 'VIKINGYFY/immortalwrt'
        required: true
        type: choice
        options:
          - VIKINGYFY/immortalwrt
          - immortalwrt/immortalwrt
          - LiBwrt/openwrt-6.x
          - qosmio/openwrt-ipq
      BRANCH:
        description: '输入源码分支'
        default: 'main'
        required: true
        type: string
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'true'
        required: true
        type: boolean

# CI 任务权限
# 给予所有任务读写权限
permissions: write-all

# CI 执行任务
jobs:
  build:
    # 任务名称将显示为输入的 CONFIG 值
    name: ${{inputs.CONFIG}}
    # 调用可复用的编译核心工作流程
    uses: ./.github/workflows/WRT-CORE.yml
    # 传递给核心工作流程的参数
    with:
      # 编译配置文件名
      WRT_CONFIG: ${{inputs.CONFIG}}
      # 默认主题
      WRT_THEME: argon
      # 默认主机名
      WRT_NAME: OpenWrt
      # 默认 WiFi 名称
      WRT_SSID: OpenWrt
      # 默认 WiFi 密码
      WRT_WORD: 12345678
      # 默认 LAN IP 地址
      WRT_IP: 10.0.0.1
      # 默认登录密码 (仅作提示，修改无效)
      WRT_PW: 无
      # 源码仓库链接
      WRT_REPO: https://github.com/${{inputs.SOURCE}}.git
      # 源码分支
      WRT_BRANCH: ${{inputs.BRANCH}}
      # 源码名称
      WRT_SOURCE: ${{inputs.SOURCE}}
      # 手动调整的插件包
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      # 是否仅测试配置文件 (不编译)
      WRT_TEST: ${{inputs.TEST}}